### ISSUE TITLE
HELP !!!!!!!!! Unable to max request

### ISSUE THREAD

**Issue by droidmanspace** [lf94/mycelium-gear#1]
hello,
Can you please help me?
I tried many times to make network call to this GET https://gateway.gear.mycelium.com/gateways/:api_gateway_id/orders/:payment_id with correct api key, payment id  and headers as X-signature and x-Nounce, But i got an error as Invalid X-Signature. I captured the x-signature from your log.
please help me !

**Comment by droidmanspace** [comment]
finally, I made the solution !!

**Comment by lf94** [comment]
Sorry I couldn't help you. I was away. Glad you figured it out :) I haven't used this code in a long time but from what I remember it is small enough to hack at. Feel free to submit a pull request if there was an API change that you fixed.
